//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyBridge.GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxyBridge.GUI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BLOCK 的本地化字符串。
        /// </summary>
        internal static string ActionBlock {
            get {
                return ResourceManager.GetString("ActionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIRECT 的本地化字符串。
        /// </summary>
        internal static string ActionDirect {
            get {
                return ResourceManager.GetString("ActionDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PROXY 的本地化字符串。
        /// </summary>
        internal static string ActionProxy {
            get {
                return ResourceManager.GetString("ActionProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR: Failed to add rule 的本地化字符串。
        /// </summary>
        internal static string AddRuleFailInfo {
            get {
                return ResourceManager.GetString("AddRuleFailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        internal static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Selected 的本地化字符串。
        /// </summary>
        internal static string ButtonRuleDelSelected {
            get {
                return ResourceManager.GetString("ButtonRuleDelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None Selected 的本地化字符串。
        /// </summary>
        internal static string ButtonRuleDesSelected {
            get {
                return ResourceManager.GetString("ButtonRuleDesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string ButtonRuleExport {
            get {
                return ResourceManager.GetString("ButtonRuleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string ButtonRuleImport {
            get {
                return ResourceManager.GetString("ButtonRuleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string ButtonRuleSelectAll {
            get {
                return ResourceManager.GetString("ButtonRuleSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Changes 的本地化字符串。
        /// </summary>
        internal static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Rule 的本地化字符串。
        /// </summary>
        internal static string ButtonSaveRule {
            get {
                return ResourceManager.GetString("ButtonSaveRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ▶ Start Test 的本地化字符串。
        /// </summary>
        internal static string ButtonStartTest {
            get {
                return ResourceManager.GetString("ButtonStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Proxy Connection 的本地化字符串。
        /// </summary>
        internal static string ButtonTestProxy {
            get {
                return ResourceManager.GetString("ButtonTestProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example: iexplore.exe; &quot;C:\some app.exe&quot;; fire*.exe; *.bin 的本地化字符串。
        /// </summary>
        internal static string ExampleApplications {
            get {
                return ResourceManager.GetString("ExampleApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example: 127.0.0.1; 192.168.1.*; 10.1.0.0-10.5.255.255; example.com; *.example.com 的本地化字符串。
        /// </summary>
        internal static string ExampleTargetHosts {
            get {
                return ResourceManager.GetString("ExampleTargetHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example: 80; 8000-9000; 3128 的本地化字符串。
        /// </summary>
        internal static string ExampleTargetPorts {
            get {
                return ResourceManager.GetString("ExampleTargetPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string LabelAction {
            get {
                return ResourceManager.GetString("LabelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        internal static string LabelActions {
            get {
                return ResourceManager.GetString("LabelActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applications 的本地化字符串。
        /// </summary>
        internal static string LabelApplications {
            get {
                return ResourceManager.GetString("LabelApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        internal static string LabelEnabled {
            get {
                return ResourceManager.GetString("LabelEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        internal static string LabelOutput {
            get {
                return ResourceManager.GetString("LabelOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password (Optional) 的本地化字符串。
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process 的本地化字符串。
        /// </summary>
        internal static string LabelProcess {
            get {
                return ResourceManager.GetString("LabelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol 的本地化字符串。
        /// </summary>
        internal static string LabelProtocol {
            get {
                return ResourceManager.GetString("LabelProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy IP Address * 的本地化字符串。
        /// </summary>
        internal static string LabelProxyIp {
            get {
                return ResourceManager.GetString("LabelProxyIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Port * 的本地化字符串。
        /// </summary>
        internal static string LabelProxyPort {
            get {
                return ResourceManager.GetString("LabelProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Type 的本地化字符串。
        /// </summary>
        internal static string LabelProxyType {
            get {
                return ResourceManager.GetString("LabelProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * Required fields 的本地化字符串。
        /// </summary>
        internal static string LabelRequiredFields {
            get {
                return ResourceManager.GetString("LabelRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SR 的本地化字符串。
        /// </summary>
        internal static string LabelSR {
            get {
                return ResourceManager.GetString("LabelSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Host 的本地化字符串。
        /// </summary>
        internal static string LabelTargetHost {
            get {
                return ResourceManager.GetString("LabelTargetHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Hosts 的本地化字符串。
        /// </summary>
        internal static string LabelTargetHosts {
            get {
                return ResourceManager.GetString("LabelTargetHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Ports 的本地化字符串。
        /// </summary>
        internal static string LabelTargetPorts {
            get {
                return ResourceManager.GetString("LabelTargetPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Connection 的本地化字符串。
        /// </summary>
        internal static string LabelTestConnection {
            get {
                return ResourceManager.GetString("LabelTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username (Optional) 的本地化字符串。
        /// </summary>
        internal static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load configuration 的本地化字符串。
        /// </summary>
        internal static string LoadConfigFailInfo {
            get {
                return ResourceManager.GetString("LoadConfigFailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration loaded successfully 的本地化字符串。
        /// </summary>
        internal static string LoadConfigSuccessInfo {
            get {
                return ResourceManager.GetString("LoadConfigSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load configuration 的本地化字符串。
        /// </summary>
        internal static string LogConfigLoadFailed {
            get {
                return ResourceManager.GetString("LogConfigLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration saved successfully 的本地化字符串。
        /// </summary>
        internal static string LogConfigSaved {
            get {
                return ResourceManager.GetString("LogConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save configuration 的本地化字符串。
        /// </summary>
        internal static string LogConfigSaveFailed {
            get {
                return ResourceManager.GetString("LogConfigSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DNS via Proxy: Disabled 的本地化字符串。
        /// </summary>
        internal static string LogDnsViaProxyDisabled {
            get {
                return ResourceManager.GetString("LogDnsViaProxyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DNS via Proxy: Enabled 的本地化字符串。
        /// </summary>
        internal static string LogDnsViaProxyEnabled {
            get {
                return ResourceManager.GetString("LogDnsViaProxyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CloudSamrtIP Initialization Success 的本地化字符串。
        /// </summary>
        internal static string LogInitialized {
            get {
                return ResourceManager.GetString("LogInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language changed to 的本地化字符串。
        /// </summary>
        internal static string LogLanguageChanged {
            get {
                return ResourceManager.GetString("LogLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR: Failed to set proxy config 的本地化字符串。
        /// </summary>
        internal static string LogProxySettingsFailed {
            get {
                return ResourceManager.GetString("LogProxySettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved proxy settings 的本地化字符串。
        /// </summary>
        internal static string LogProxySettingsSaved {
            get {
                return ResourceManager.GetString("LogProxySettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restored proxy settings 的本地化字符串。
        /// </summary>
        internal static string LogRestoredProxySettings {
            get {
                return ResourceManager.GetString("LogRestoredProxySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restored {0} proxy rule(s) 的本地化字符串。
        /// </summary>
        internal static string LogRestoredRules {
            get {
                return ResourceManager.GetString("LogRestoredRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added rule 的本地化字符串。
        /// </summary>
        internal static string LogRuleAdded {
            get {
                return ResourceManager.GetString("LogRuleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR: Failed to add rule 的本地化字符串。
        /// </summary>
        internal static string LogRuleAddFailed {
            get {
                return ResourceManager.GetString("LogRuleAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 service started successfully 的本地化字符串。
        /// </summary>
        internal static string LogServiceStarted {
            get {
                return ResourceManager.GetString("LogServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR: Failed to start service 的本地化字符串。
        /// </summary>
        internal static string LogServiceStartFailed {
            get {
                return ResourceManager.GetString("LogServiceStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 with auth 的本地化字符串。
        /// </summary>
        internal static string LogWithAuth {
            get {
                return ResourceManager.GetString("LogWithAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About CloudSmartIP 的本地化字符串。
        /// </summary>
        internal static string MenuAboutProxyBridge {
            get {
                return ResourceManager.GetString("MenuAboutProxyBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates 的本地化字符串。
        /// </summary>
        internal static string MenuCheckUpdates {
            get {
                return ResourceManager.GetString("MenuCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close to System Tray 的本地化字符串。
        /// </summary>
        internal static string MenuCloseToTray {
            get {
                return ResourceManager.GetString("MenuCloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DNS via Proxy 的本地化字符串。
        /// </summary>
        internal static string MenuDnsViaProxy {
            get {
                return ResourceManager.GetString("MenuDnsViaProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Traffic Logging 的本地化字符串。
        /// </summary>
        internal static string MenuEnableTrafficLogging {
            get {
                return ResourceManager.GetString("MenuEnableTrafficLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Localhost via Proxy 的本地化字符串。
        /// </summary>
        internal static string MenuLocalhostViaProxy {
            get {
                return ResourceManager.GetString("MenuLocalhostViaProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy 的本地化字符串。
        /// </summary>
        internal static string MenuProxy {
            get {
                return ResourceManager.GetString("MenuProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Rules 的本地化字符串。
        /// </summary>
        internal static string MenuProxyRules {
            get {
                return ResourceManager.GetString("MenuProxyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Settings 的本地化字符串。
        /// </summary>
        internal static string MenuProxySettings {
            get {
                return ResourceManager.GetString("MenuProxySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run at Startup 的本地化字符串。
        /// </summary>
        internal static string MenuRunAtStartup {
            get {
                return ResourceManager.GetString("MenuRunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e.g., 127.0.0.1 的本地化字符串。
        /// </summary>
        internal static string PlaceholderIpAddress {
            get {
                return ResourceManager.GetString("PlaceholderIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave empty if no auth required 的本地化字符串。
        /// </summary>
        internal static string PlaceholderNoAuth {
            get {
                return ResourceManager.GetString("PlaceholderNoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e.g., 1080 的本地化字符串。
        /// </summary>
        internal static string PlaceholderPort {
            get {
                return ResourceManager.GetString("PlaceholderPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both (TCP + UDP) 的本地化字符串。
        /// </summary>
        internal static string ProtocolBoth {
            get {
                return ResourceManager.GetString("ProtocolBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TCP 的本地化字符串。
        /// </summary>
        internal static string ProtocolTCP {
            get {
                return ResourceManager.GetString("ProtocolTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UDP 的本地化字符串。
        /// </summary>
        internal static string ProtocolUDP {
            get {
                return ResourceManager.GetString("ProtocolUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔍 Search activity logs... 的本地化字符串。
        /// </summary>
        internal static string SearchActivityPlaceholder {
            get {
                return ResourceManager.GetString("SearchActivityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔍 Search connections... 的本地化字符串。
        /// </summary>
        internal static string SearchConnectionsholder {
            get {
                return ResourceManager.GetString("SearchConnectionsholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔍 Search connections... 的本地化字符串。
        /// </summary>
        internal static string SearchConnectionsPlaceholder {
            get {
                return ResourceManager.GetString("SearchConnectionsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR: Failed to set proxy config 的本地化字符串。
        /// </summary>
        internal static string SetProxyConfigFail {
            get {
                return ResourceManager.GetString("SetProxyConfigFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR: Failed to start SmartIP service 的本地化字符串。
        /// </summary>
        internal static string StartProxyFail {
            get {
                return ResourceManager.GetString("StartProxyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activity Logs 的本地化字符串。
        /// </summary>
        internal static string TabActivity {
            get {
                return ResourceManager.GetString("TabActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connections 的本地化字符串。
        /// </summary>
        internal static string TabConnections {
            get {
                return ResourceManager.GetString("TabConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Rules 的本地化字符串。
        /// </summary>
        internal static string WindowProxyRules {
            get {
                return ResourceManager.GetString("WindowProxyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Settings 的本地化字符串。
        /// </summary>
        internal static string WindowProxySettings {
            get {
                return ResourceManager.GetString("WindowProxySettings", resourceCulture);
            }
        }
    }
}
